In [82]:
import pandas as pd

# Netflix Data from 2008 to 2021

### [未清理版本](https://www.kaggle.com/datasets/shivamb/netflix-shows)
### [已清理版本](https://www.kaggle.com/datasets/ariyoomotade/netflix-data-cleaning-analysis-and-visualization)
### [視覺化範例](https://public.tableau.com/app/profile/abdulrasaq.ariyo/viz/NetflixTVShowsMovies_16615029026580/NetflixDashboard)

### 欄位 
- show_id
- type
- title
- director
- country
- date_added
- release_year
- rating
- duration
- listed_in

### 備註
- 8790 X 10

In [120]:
# https://www.kaggle.com/datasets/ariyoomotade/netflix-data-cleaning-analysis-and-visualization

df = pd.read_csv("./netflix.csv")
df["listed_in"] = df["listed_in"].apply(lambda x: x.split(", "))
df.sort_values("release_year", ascending=False)
df["date_added"] = pd.to_datetime(df["date_added"])#.dt.strftime('%Y-%m-%d')
df

,show_id,type,title,director,country,date_added,release_year,rating,duration,listed_in
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,United States,2021-09-25,2020,PG-13,90 min,[Documentaries]
1,s3,TV Show,Ganglands,Julien Leclercq,France,2021-09-24,2021,TV-MA,1 Season,"[Crime TV Shows, International TV Shows, TV Ac..."
2,s6,TV Show,Midnight Mass,Mike Flanagan,United States,2021-09-24,2021,TV-MA,1 Season,"[TV Dramas, TV Horror, TV Mysteries]"
3,s14,Movie,Confessions of an Invisible Girl,Bruno Garotti,Brazil,2021-09-22,2021,TV-PG,91 min,"[Children & Family Movies, Comedies]"
4,s8,Movie,Sankofa,Haile Gerima,United States,2021-09-24,1993,TV-MA,125 min,"[Dramas, Independent Movies, International Mov..."
...,...,...,...,...,...,...,...,...,...,...
8785,s8797,TV Show,Yunus Emre,Not Given,Turkey,2017-01-17,2016,TV-PG,2 Seasons,"[International TV Shows, TV Dramas]"
8786,s8798,TV Show,Zak Storm,Not Given,United States,2018-09-13,2016,TV-Y7,3 Seasons,[Kids' TV]
8787,s8801,TV Show,Zindagi Gulzar Hai,Not Given,Pakistan,2016-12-15,2012,TV-PG,1 Season,"[International TV Shows, Romantic TV Shows, TV..."
8788,s8784,TV Show,Yoko,Not Given,Pakistan,2018-06-23,2016,TV-Y,1 Season,[Kids' TV]
8789,s8786,TV Show,YOM,Not Given,Pakistan,2018-06-07,2016,TV-Y7,1 Season,[Kids' TV]

# IMDB Dataset 2023

### [已清理版本](https://www.kaggle.com/datasets/adriankiezun/imdb-dataset-2023)

### 欄位 
- **id**: movie's ID used by IMDB repository
- **primaryTitle**: title in English
- **originalTitle**: original title in native language
- **isAdult**: parental guidance
- **runtimeMinutes**: total runtime in minutes
- **genres**: genres
- **averageRating**: final rating, based on all the ratings
- **numVotes**: total number of votes (ratings)
- **budget**: total budget in USD
- **gross**: total gross worldwide in USD
- **release_date**: release date, first occurrence
- **directors**: directors

### 備註
- 3384 x 12

In [133]:
# https://www.kaggle.com/datasets/adriankiezun/imdb-dataset-2023
df = pd.read_csv("./imdb.csv")
df

,id,primaryTitle,originalTitle,isAdult,runtimeMinutes,genres,averageRating,numVotes,budget,gross,release_date,directors
0,tt0035423,Kate & Leopold,Kate & Leopold,0,118,"Comedy,Fantasy,Romance",6.4,87925,48000000,76019048.0,"December 11, 2001",James Mangold
1,tt0065421,The Aristocats,The AristoCats,0,78,"Adventure,Animation,Comedy",7.1,111758,4000000,35459543.0,"December 11, 1970",Wolfgang Reitherman
2,tt0065938,Kelly's Heroes,Kelly's Heroes,0,144,"Adventure,Comedy,War",7.6,52628,4000000,5200000.0,"January 1, 1970",Brian G. Hutton
3,tt0066026,M*A*S*H,M*A*S*H,0,116,"Comedy,Drama,War",7.4,75784,3500000,81600000.0,"January 25, 1970",Robert Altman
4,tt0066206,Patton,Patton,0,172,"Biography,Drama,War",7.9,106476,12000000,61749765.0,"February 4, 1970",Franklin J. Schaffner
...,...,...,...,...,...,...,...,...,...,...,...,...
3343,tt9770150,Nomadland,Nomadland,0,107,Drama,7.3,175977,5000000,39458207.0,"September 11, 2020",Chloé Zhao
3344,tt9777666,The Tomorrow War,The Tomorrow War,0,138,"Action,Adventure,Drama",6.6,220617,200000000,14400000.0,"June 30, 2021",Chris McKay
3345,tt9784798,Judas and the Black Messiah,Judas and the Black Messiah,0,126,"Biography,Drama,History",7.4,88568,26000000,7478009.0,"February 1, 2021",Shaka King
3346,tt9844522,Escape Room: Tournament of Champions,Escape Room: Tournament of Champions,0,88,"Action,Adventure,Horror",5.7,56955,15000000,65774490.0,"July 1, 2021",Adam Robitel
3347,tt9893250,I Care a Lot,I Care a Lot,0,118,"Comedy,Crime,Drama",6.4,141433,14000000,1351662.0,"September 12, 2020",J Blakeson

# Anime Dataset

### [未清理版本](https://www.kaggle.com/datasets/arnavvvvv/anime-dataset?select=animes.csv)

### 欄位 
- **uid**
- **title**
- **synopsis**
- **genre**
- **aired**
- **episodes**
- **members**
- **popularity**
- **ranked**
- **score**
- **img_url**
- **link**

### 備註
- 13731 × 12 
- **每部動漫有圖片連結**

In [141]:
# https://www.kaggle.com/datasets/arnavvvvv/anime-dataset?select=animes.csv
df = pd.read_csv("./animes.csv")
df.shape[0], df.dropna().shape[0]
df = df.drop_duplicates().sort_values("ranked")
df.dropna()

,uid,title,synopsis,genre,aired,episodes,members,popularity,ranked,score,img_url,link
3,5114,Fullmetal Alchemist: Brotherhood,"""In order for something to be obtained, someth...","['Action', 'Military', 'Adventure', 'Comedy', ...","Apr 5, 2009 to Jul 4, 2010",64.0,1615084,4,1.0,9.23,https://cdn.myanimelist.net/images/anime/1223/...,https://myanimelist.net/anime/5114/Fullmetal_A...
773,9253,Steins;Gate,The self-proclaimed mad scientist Rintarou Oka...,"['Thriller', 'Sci-Fi']","Apr 6, 2011 to Sep 14, 2011",24.0,1331710,7,2.0,9.11,https://cdn.myanimelist.net/images/anime/5/731...,https://myanimelist.net/anime/9253/Steins_Gate
772,11061,Hunter x Hunter (2011),Hunter x Hunter is set in a world where Hunte...,"['Action', 'Adventure', 'Fantasy', 'Shounen', ...","Oct 2, 2011 to Sep 24, 2014",148.0,1052761,20,3.0,9.11,https://cdn.myanimelist.net/images/anime/11/33...,https://myanimelist.net/anime/11061/Hunter_x_H...
771,32281,Kimi no Na wa.,"Mitsuha Miyamizu, a high school girl, yearns t...","['Romance', 'Supernatural', 'School', 'Drama']","Aug 26, 2016",1.0,1139878,15,4.0,9.09,https://cdn.myanimelist.net/images/anime/5/870...,https://myanimelist.net/anime/32281/Kimi_no_Na_wa
770,38524,Shingeki no Kyojin Season 3 Part 2,Seeking to restore humanity’s diminishing hope...,"['Action', 'Drama', 'Fantasy', 'Military', 'My...","Apr 29, 2019 to Jul 1, 2019",10.0,446370,175,5.0,9.07,https://cdn.myanimelist.net/images/anime/1517/...,https://myanimelist.net/anime/38524/Shingeki_n...
...,...,...,...,...,...,...,...,...,...,...,...,...
14328,28543,Zukkoke Sannin-gumi no Hi Asobi Boushi Daisakusen,An educational fire prevention video for kids ...,"['Kids', 'Drama']",2014,1.0,133,14676,14670.0,5.50,https://cdn.myanimelist.net/images/anime/13/68...,https://myanimelist.net/anime/28543/Zukkoke_Sa...
14871,35099,Zukkoke Sannin-gumi no Jitensha Kyoushitsu,An educational bicycle safety video for kids f...,"['Drama', 'Kids']",2016,1.0,94,15470,14671.0,6.35,https://cdn.myanimelist.net/images/anime/10/84...,https://myanimelist.net/anime/35099/Zukkoke_Sa...
14870,35149,Zukkoke Sannin-gumi no Koutsuu Anzen,An traffic safety video for kids featuring the...,"['Drama', 'Kids']",Not available,1.0,91,15532,14672.0,5.79,https://cdn.myanimelist.net/images/anime/5/847...,https://myanimelist.net/anime/35149/Zukkoke_Sa...
14869,18967,Zukkoke Sannin-gumi: Zukkoke Jikuu Bouken,Three reporters from the school paper get tran...,"['Comedy', 'Historical', 'Sci-Fi']","Apr 1, 1988",1.0,178,13827,14674.0,6.48,https://cdn.myanimelist.net/images/anime/4/508...,https://myanimelist.net/anime/18967/Zukkoke_Sa...
14868,13455,Zumomo to Nupepe,No synopsis has been added for this series yet...,['Comedy'],"Apr 3, 2012 to Feb 26, 2013",32.0,252,12647,14675.0,6.23,https://cdn.myanimelist.net/images/anime/7/469...,https://myanimelist.net/anime/13455/Zumomo_to_...

# Customer Segmentation Data

### [已清理版本](https://www.kaggle.com/datasets/ravalsmit/customer-segmentation-data)

### 欄位 
- **Customer ID**
- **Age**
- **Gender**
- **Marital Status**
- **Education Level**
- **Geographic Information**
- **Occupation**
- **Income Level**
- **Behavioral Data**
- **Purchase History**
- **Interactions with Customer Service**
- **Insurance Products Owned**
- **Coverage Amount**
- **Premium Amount**
- **Policy Type**
- **Customer Preferences**
- **Preferred Communication Channel**
- **Preferred Contact Time**
- **Preferred Language**
- **Segmentation Group**

### 備註
- 53503 × 20

In [145]:
# https://www.kaggle.com/datasets/ravalsmit/customer-segmentation-data
df = pd.read_csv("./customer.csv")
df.dropna()

,Customer ID,Age,Gender,Marital Status,Education Level,Geographic Information,Occupation,Income Level,Behavioral Data,Purchase History,Interactions with Customer Service,Insurance Products Owned,Coverage Amount,Premium Amount,Policy Type,Customer Preferences,Preferred Communication Channel,Preferred Contact Time,Preferred Language,Segmentation Group
0,84966,23,Female,Married,Associate Degree,Mizoram,Entrepreneur,70541,policy5,04-10-2018,Phone,policy2,366603,2749,Group,Email,In-Person Meeting,Afternoon,English,Segment5
1,95568,26,Male,Widowed,Doctorate,Goa,Manager,54168,policy5,11-06-2018,Chat,policy1,780236,1966,Group,Mail,In-Person Meeting,Morning,French,Segment5
2,10544,29,Female,Single,Associate Degree,Rajasthan,Entrepreneur,73899,policy5,06-05-2021,Email,policy3,773926,4413,Group,Email,Mail,Evening,German,Segment3
3,77033,20,Male,Divorced,Bachelor's Degree,Sikkim,Entrepreneur,63381,policy5,09-02-2018,Chat,policy2,787815,4342,Family,Text,In-Person Meeting,Anytime,French,Segment3
4,88160,25,Female,Separated,Bachelor's Degree,West Bengal,Manager,38794,policy1,09-10-2018,Chat,policy4,366506,1276,Family,Email,Text,Weekends,English,Segment2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
53498,44809,35,Female,Divorced,Associate Degree,Andaman and Nicobar Islands,Salesperson,120850,policy3,01-01-2019,Mobile App,policy1,586401,4404,Family,In-Person Meeting,Phone,Afternoon,German,Segment5
53499,65485,61,Male,Single,Doctorate,Himachal Pradesh,Entrepreneur,122309,policy5,5/18/2021,Mobile App,policy4,637733,1285,Group,Text,Mail,Afternoon,German,Segment1
53500,26213,25,Male,Divorced,Doctorate,Assam,Teacher,49258,policy2,11/27/2018,In-Person,policy1,631057,4407,Individual,Text,Text,Weekends,French,Segment4
53501,63136,42,Male,Married,Doctorate,Andhra Pradesh,Artist,66301,policy4,06-04-2021,In-Person,policy1,730385,4482,Business,Mail,Phone,Morning,French,Segment5
53502,62125,20,Male,Divorced,Doctorate,Daman and Diu,Salesperson,136632,policy2,10/14/2022,Phone,policy1,743262,4499,Group,Text,In-Person Meeting,Evening,German,Segment2

In [95]:
# https://cabu.kcg.gov.tw/web/StatRptsFileList.aspx?catId=16504724-317b-4d57-8396-bd0af78b5ed4
#高雄統計

# Disney+ Movies and TV Shows

### [未清理版本](https://www.kaggle.com/datasets/shivamb/disney-movies-and-tv-shows/data)

### 欄位 
- **show_id**
- **type**
- **title**
- **director**
- **cast**
- **country**
- **date_added**
- **release_year**
- **rating**
- **duration**
- **listed_in**
- **description**

### 備註
- 1450 × 12

In [151]:
# https://www.kaggle.com/datasets/shivamb/disney-movies-and-tv-shows/data
df = pd.read_csv("disney_plus.csv")
df

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Duck the Halls: A Mickey Mouse Christmas Special,"Alonso Ramirez Ramos, Dave Wasson","Chris Diamantopoulos, Tony Anselmo, Tress MacN...",NaN,"November 26, 2021",2016,TV-G,23 min,"Animation, Family",Join Mickey and the gang as they duck the halls!
1,s2,Movie,Ernest Saves Christmas,John Cherry,"Jim Varney, Noelle Parker, Douglas Seale",NaN,"November 26, 2021",1988,PG,91 min,Comedy,Santa Claus passes his magic bag to a new St. ...
2,s3,Movie,Ice Age: A Mammoth Christmas,Karen Disher,"Raymond Albert Romano, John Leguizamo, Denis L...",United States,"November 26, 2021",2011,TV-G,23 min,"Animation, Comedy, Family",Sid the Sloth is on Santa's naughty list.
3,s4,Movie,The Queen Family Singalong,Hamish Hamilton,"Darren Criss, Adam Lambert, Derek Hough, Alexa...",NaN,"November 26, 2021",2021,TV-PG,41 min,Musical,"This is real life, not just fantasy!"
4,s5,TV Show,The Beatles: Get Back,NaN,"John Lennon, Paul McCartney, George Harrison, ...",NaN,"November 25, 2021",2021,NaN,1 Season,"Docuseries, Historical, Music",A three-part documentary from Peter Jackson ca...
...,...,...,...,...,...,...,...,...,...,...,...,...
1445,s1446,Movie,X-Men Origins: Wolverine,Gavin Hood,"Hugh Jackman, Liev Schreiber, Danny Huston, wi...","United States, United Kingdom","June 4, 2021",2009,PG-13,108 min,"Action-Adventure, Family, Science Fiction",Wolverine unites with legendary X-Men to fight...
1446,s1447,Movie,Night at the Museum: Battle of the Smithsonian,Shawn Levy,"Ben Stiller, Amy Adams, Owen Wilson, Hank Azar...","United States, Canada","April 2, 2021",2009,PG,106 min,"Action-Adventure, Comedy, Family",Larry Daley returns to rescue some old friends...
1447,s1448,Movie,Eddie the Eagle,Dexter Fletcher,"Tom Costello, Jo Hartley, Keith Allen, Dickon ...","United Kingdom, Germany, United States","December 18, 2020",2016,PG-13,107 min,"Biographical, Comedy, Drama","True story of Eddie Edwards, a British ski-jum..."
1448,s1449,Movie,Bend It Like Beckham,Gurinder Chadha,"Parminder Nagra, Keira Knightley, Jonathan Rhy...","United Kingdom, Germany, United States","September 18, 2020",2003,PG-13,112 min,"Buddy, Comedy, Coming of Age",Despite the wishes of their traditional famili...
1449,s1450,Movie,Captain Sparky vs. The Flying Saucers,Mark Waring,Charlie Tahan,United States,"April 1, 2020",2012,TV-G,2 min,"Action-Adventure, Animals & Nature, Animation",View one of Sparky's favorite home movies.

# 台灣各縣市提供之開放資料

### [已清理資料-縣市](https://github.com/slowpoke1025/dv/blob/main/counties.csv)
### [全國資料](https://winstacity.dgbas.gov.tw/DgbasWeb/ZWeb/StateFile_ZWeb.aspx?Type=table&Area=)
### [高雄各區資料](https://cabu.kcg.gov.tw/web/StatRptsFileList.aspx?catId=16504724-317b-4d57-8396-bd0af78b5ed4)


### [視覺化範例1](https://gis.ris.gov.tw/dashboard.html)
### [視覺化範例2](https://plotdb.com/chart/12706/v1/)



### 欄位 
- **地區**
- **土地面積(平方公里)**
- **戶籍登記戶數(戶)**
- **戶籍登記人口數(人)**
- **0-14歲人口數(人)**
- **15-64歲人口數(人)**
- **65歲以上人口數(人)**
- **幼年人口比率(0-14歲)(％)**
- **青壯年人口比率(15-64歲)(％)**
- **老年人口比率(65歲以上)(％)**
- **扶養比()**
- **老化指數()**
- **男性人口(人)**
- **女性人口(人)**
- **性比例(女=100)**
- **出生登記數(人)**
- **死亡登記數(人)**
- **粗出生率(‰)**
- **粗死亡率(‰)**
- **自然增加率(‰)**
- **遷入人口數(人)**
- **遷出人口數(人)**
- **社會增加率(‰)**
- **人口總增加率(‰)**
- **人口密度(人/平方公里)**
- **一般生育率(‰)**
- **結婚登記對數(對)**
- **離婚登記對數(對)**
- **相同性別結婚登記對數(對)**
- **粗結婚率(‰)**
- **粗離婚率(‰)**
- **勞動力人口數(千人)**
- **失業率(％)**
- **就業人口數(千人)**
- **就業者之行業結構-工業(％)**
- **就業者之行業結構-服務業(％)**
- **就業者之行業結構-農林漁牧業(％)**
- **就業者之教育程度結構-大專及以上(％)**
- **就業者之教育程度結構-高中(職)(％)**
- **就業者之教育程度結構-國中及以下(％)**
- **總工時(小時)**
- **公教人員人數(人)**
- **刑案發生數(件)**
- **刑案破獲數(件)**
- **嫌疑犯人數(人)**
- **刑案發生率(件/十萬人)**
- **刑案破獲率(％)**
- **犯罪人口率(人/十萬人)**
- **少年犯罪人口率(人/十萬人)**
- **青年犯罪人口率(人/十萬人)**
- **成年犯罪人口率(人/十萬人)**
- **道路交通事故肇事總件數(件)**
- **鄉鎮市區數(個)**
- **低收入戶人口數(人)**
- **森林面積(公頃)**
- **森林地占土地面積比率(％)**
- **電力用戶數(戶)**
- **電力售電量(百萬度)**
- **電力用戶平均每戶售電量(萬度/戶)**

### 備註
- 可結合台灣縣市、鄉鎮區地圖，做地理空間視覺化
- 篩選特定區域進行視覺化 (ex:整個高雄市、鹽埕區)
- 可再結合其他來源縣市、鄉鎮資料
- ex: 各地氣象狀況、人口、性別比、出生死亡率、移出移入、老人比例等等

In [281]:
df = pd.read_csv("county.csv")
df = df.drop(df.columns[0], axis=1).drop([0,1], axis=0)
df = df.iloc[0:23]
df = df.rename({df.columns[0]:"地區"}, axis = 1).set_index("地區")
df = df.replace(',', '', regex=True)
df = df.drop(["農戶數(戶)","觀光旅館平均房價(元)", "歲入(百萬元)", "耕地率(％)"], axis=1)
df = df.astype("float64")
df

,土地面積(平方公里),戶籍登記戶數(戶),戶籍登記人口數(人),0-14歲人口數(人),15-64歲人口數(人),65歲以上人口數(人),幼年人口比率(0-14歲)(％),青壯年人口比率(15-64歲)(％),老年人口比率(65歲以上)(％),扶養比(),...,青年犯罪人口率(人/十萬人),成年犯罪人口率(人/十萬人),道路交通事故肇事總件數(件),鄉鎮市區數(個),低收入戶人口數(人),森林面積(公頃),森林地占土地面積比率(％),電力用戶數(戶),電力售電量(百萬度),電力用戶平均每戶售電量(萬度/戶)
地區,,,,,,,,,,,,,,,,,,,,,
臺灣地區,36013.73,9042821.0,23109362.0,2805896.0,16242847.0,4060619.0,12.14,70.29,17.57,42.27,...,2173.93,1360.45,374787.0,358.0,288211.0,2189243.0,60.79,329681.0,168417.0,51.49
新北市,2052.57,1638908.0,3995551.0,460811.0,2853380.0,681360.0,11.53,71.41,17.05,40.03,...,1213.37,773.97,45727.0,29.0,35091.0,155483.0,75.75,37713.0,10279.0,27.47
臺北市,271.80,1050981.0,2480681.0,312209.0,1649878.0,518594.0,12.59,66.51,20.91,50.36,...,3683.63,1796.17,25141.0,12.0,44476.0,11491.0,42.28,23517.0,8305.0,35.36
桃園市,1220.95,878466.0,2281464.0,319714.0,1636005.0,325745.0,14.01,71.71,14.28,39.45,...,1711.58,1209.12,49110.0,13.0,28305.0,47134.0,38.60,18468.0,23308.0,128.04
臺中市,2214.90,1033821.0,2814459.0,379633.0,2010536.0,424290.0,13.49,71.44,15.08,39.99,...,2004.07,1110.22,44618.0,29.0,44247.0,113963.0,51.45,30653.0,25305.0,83.44
臺南市,2191.65,716543.0,1852997.0,213467.0,1305385.0,334145.0,11.52,70.45,18.03,41.95,...,2993.66,1704.47,44685.0,37.0,15214.0,54148.0,24.71,30855.0,26758.0,87.20
高雄市,2951.85,1136785.0,2728137.0,309049.0,1919113.0,499975.0,11.33,70.35,18.33,42.16,...,1761.76,1033.88,38080.0,38.0,29344.0,170523.0,57.77,34956.0,24614.0,71.03
宜蘭縣,2143.63,176074.0,449062.0,51141.0,314394.0,83527.0,11.39,70.01,18.60,42.83,...,3265.61,1960.82,8366.0,12.0,5081.0,168384.0,78.55,5320.0,2237.0,42.64
新竹縣,1427.54,215177.0,580503.0,91302.0,410033.0,79168.0,15.73,70.63,13.64,41.57,...,1674.88,1338.48,11124.0,13.0,4241.0,104211.0,73.00,5315.0,9262.0,179.06
苗栗縣,1820.31,197025.0,535132.0,62217.0,375010.0,97905.0,11.63,70.08,18.30,42.70,...,1712.88,1360.45,7748.0,18.0,5851.0,125946.0,69.19,4213.0,6264.0,152.40
彰化縣,1074.40,402420.0,1245239.0,151252.0,870239.0,223748.0,12.15,69.89,17.97,43.09,...,1856.56,1457.17,24442.0,26.0,12594.0,10104.0,9.40,42755.0,8244.0,19.35
南投縣,4106.44,179907.0,479595.0,49333.0,333698.0,96564.0,10.29,69.58,20.13,43.72,...,3002.04,1894.23,7655.0,13.0,4343.0,303186.0,73.83,6079.0,1665.0,28.11
雲林縣,1290.83,245397.0,664092.0,70283.0,460188.0,133621.0,10.58,69.30,20.12,44.31,...,2383.23,1549.76,10841.0,20.0,11050.0,12609.0,9.77,19977.0,4686.0,23.66
嘉義縣,1903.64,185398.0,488158.0,41949.0,340307.0,105902.0,8.59,69.71,21.69,43.45,...,2558.30,1765.72,7995.0,18.0,3577.0,79888.0,41.97,20796.0,2302.0,11.12
屏東縣,2775.60,295132.0,798703.0,80576.0,562552.0,155575.0,10.09,70.43,19.48,41.98,...,1757.40,1301.83,16155.0,33.0,15651.0,156194.0,56.27,31995.0,2820.0,8.85
臺東縣,3515.25,84259.0,212551.0,23604.0,149108.0,39839.0,11.11,70.15,18.74,42.55,...,2489.63,1534.11,4305.0,16.0,6829.0,286984.0,81.64,2544.0,441.0,17.84
花蓮縣,4628.57,128185.0,318892.0,36247.0,221912.0,60733.0,11.37,69.59,19.05,43.70,...,2745.19,1523.45,6139.0,13.0,9392.0,372781.0,80.54,3113.0,1597.0,52.59
澎湖縣,126.86,42840.0,107223.0,10634.0,77008.0,19581.0,9.92,71.82,18.26,39.24,...,2076.01,1301.31,1000.0,6.0,1292.0,3242.0,25.55,1730.0,194.0,11.27
基隆市,132.76,157172.0,361526.0,35582.0,256162.0,69782.0,9.84,70.86,19.30,41.13,...,3154.40,1802.11,3951.0,7.0,5006.0,9395.0,70.77,2502.0,577.0,23.28
新竹市,104.15,175991.0,452473.0,73597.0,314823.0,64053.0,16.27,69.58,14.16,43.72,...,1920.73,1195.75,9126.0,3.0,4026.0,2804.0,26.92,4781.0,9107.0,190.40
嘉義市,60.03,102340.0,262924.0,33296.0,183116.0,46512.0,12.66,69.65,17.69,43.58,...,3359.59,1991.17,3105.0,2.0,2601.0,773.0,12.88,2399.0,453.0,18.93
金門縣,151.66,42999.0,141295.0,11845.0,106233.0,23217.0,8.38,75.19,16.43,33.00,...,1777.07,1202.26,999.0,6.0,409.0,6452.0,42.54,2356.0,122.0,5.22
連江縣,28.80,3630.0,13983.0,1428.0,10598.0,1957.0,10.21,75.79,14.00,31.94,...,2609.96,1176.74,58.0,4.0,83.0,1393.0,48.37,271.0,34.0,12.73